import {
     API_BASE_URL,
     SITE_BASE_PATH,
     MAINTENANCE_MESSAGE,
     IN_MAINTENANCE_MODE
} from "../config";

export const BASE_URL = API_BASE_URL;
export const BASE_PATH = SITE_BASE_PATH;
export const IS_MAITENANCE_MODE_ENABLED = IN_MAINTENANCE_MODE;
export const MAINTENANCE_MESSAGE_TO_SHOW = MAINTENANCE_MESSAGE;
